// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbspdoyyrouhackdaznt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNic3Bkb3l5cm91aGFja2Rhem50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzgxNjIsImV4cCI6MjA2OTcxNDE2Mn0.Gd4sprTgkY6k3T6SRhDXBaOG8uDSxLn2zBXAUceCF5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});